@baseUrl = http://localhost:8080

### 구독 생성
POST {{baseUrl}}/subscriptions
Content-Type: application/json
Authorization: Basic customer1 password

{
  "productId": 1,
  "cycle": {
    "unit": "ONE_MONTH",
    "interval": 1
  }
}

> {%
    client.test("구독 생성 성공", function() {
        client.assert(response.status === 201, "응답 상태는 201이어야 합니다.");
    });

    client.global.set("subscriptionId", response.body.subscriptionId);
%}

### 인증 없이 구독 조회
GET {{baseUrl}}/subscriptions/{{subscriptionId}}

> {%
    client.test("인증되지 않은 사용자는 접근할 수 없다", function() {
        client.assert(
            response.status === 401,
            "Expected 401 but got " + response.status
        );
    });
%}

### 구독 조회
GET {{baseUrl}}/subscriptions/{{subscriptionId}}
Authorization: Basic customer1 password

> {%
    client.test("생성된 구독은 활성 상태", function() {
        client.assert(response.status === 200, "응답 상태는 200이어야 합니다.");
        client.assert(response.body.status === "ACTIVE", "구독 상태는 ACTIVE여야 합니다.");
    });
%}

### 구독 일시정지
PATCH {{baseUrl}}/subscriptions/hold?subscriptionId={{subscriptionId}}
Authorization: Basic customer1 password

> {%
    client.test("구독 일시정지 성공", function() {
        client.assert(response.status === 200, "응답 상태는 200이어야 합니다.");
    });
%}

### 구독 재개
PATCH {{baseUrl}}/subscriptions/resume?subscriptionId={{subscriptionId}}
Authorization: Basic customer1 password

> {%
    client.test("구독 재개 성공", function() {
        client.assert(response.status === 200, "응답 상태는 200이어야 합니다.");
    });
%}