@baseUrl = http://localhost:8080

### 구독 생성
POST {{baseUrl}}/
Content-Type: application/json

{
  "customerId": 1,
  "productId": 1,
  "cycle": {
    "unit": "ONE_MONTH",
    "interval": 1
  }
}

> {% 
    client.test("구독 생성 성공", function() {
        client.assert(response.status === 200, "응답 상태는 200이어야 합니다.");
    });
%}
